# Schema for the configuration files of the ECK module.

# This schema tells the config system how to read the config YML files.

eck.eck_entity_type.*:
  type: mapping
  label: 'ECK Entity Type'
  mapping:
    id:
      type: string
      label: 'Id'
    uuid:
      type: string
      label: 'uuid'
    label:
      type: label
      label: 'Name'

eck.eck_type.*:
  type: config_entity
  label: 'ECK Entity Type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Explanation or submission guidelines'
